language: node_js

services:
  - docker
script:
  - docker build -t client .
  - docker ps -a
  - docker run --env AWS_ACCESS_KEY_ID=$AWS_KEY --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET --env AWS_DEFAULT_REGION=$AWS_REGION client
install: skip
