language: node_js

node_js:
  - "10"

services:
  - docker

jobs:
  include:
    - stage: test
      name: 'Lint & Test'
      script:
        - docker build -t client:latest -f ./Dockerfile.dev .
    - stage: deploy
      name: 'Deploy to AWS'
      script:
        - docker build -t client:latest .
        - docker ps -a
        - docker run --env AWS_ACCESS_KEY_ID=$AWS_KEY --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET --env AWS_DEFAULT_REGION=$AWS_REGION client
      if: branch = master

install: skip
