language: node_js
node_js:
  - 10.15.0
before_install:
  - cd ./docs
  - npm i -g typescript
install: yarn
script: npm run build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "anchor.retailmenot.design"
  skip_cleanup: true
  acl: public_read
  local_dir: public
